# Generated by Django 4.0.3 on 2023-07-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qanda',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qanda',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qanda',
            name='url',
        ),
        migrations.AlterField(
            model_name='qanda',
            name='cdate',
            field=models.DateTimeField(),
        ),
    ]
