# Generated by Django 4.0 on 2023-07-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_date',
            new_name='cdate',
        ),
    ]
