# Generated by Django 4.0 on 2023-07-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_qanda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qanda',
        ),
    ]
