# Generated by Django 4.0 on 2023-07-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_delete_qanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locker_used',
            field=models.IntegerField(default=0, verbose_name='사물함'),
        ),
    ]
