# Generated by Django 4.0 on 2023-07-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_user_locker_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='locker_used',
            new_name='locker_number',
        ),
    ]
