# Generated by Django 4.0 on 2023-07-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_rename_locker_used_user_locker_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='locker_number',
        ),
        migrations.AddField(
            model_name='user',
            name='locker_id',
            field=models.IntegerField(default=0, verbose_name='사물함 번호'),
        ),
    ]
