# Generated by Django 4.0 on 2023-07-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_user_locker_number_user_locker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_student_pay',
        ),
    ]
