# Generated by Django 4.0 on 2023-07-13 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0009_delete_qanda'),
        ('locker', '0002_remove_users_student_number_delete_lockers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_number', models.IntegerField()),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
        ),
    ]
