# Generated by Django 4.0 on 2023-07-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locker',
        ),
    ]
