# Generated by Django 4.0 on 2023-07-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0007_remove_locker_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locker',
        ),
    ]
