# Generated by Django 4.0 on 2023-08-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csegallary', '0002_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
