# Generated by Django 4.2.6 on 2023-11-28 15:12

from django.db import migrations, models
import term2023.utils


class Migration(migrations.Migration):
    dependencies = [
        ("term2023", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term2023question",
            name="image",
            field=models.FileField(upload_to=term2023.utils.file_name_creater),
        ),
    ]
