# Generated by Django 4.2 on 2023-07-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M610Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('MON', models.IntegerField()),
                ('TUE', models.IntegerField()),
                ('WED', models.IntegerField()),
                ('THU', models.IntegerField()),
                ('FRI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M615Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('MON', models.IntegerField()),
                ('TUE', models.IntegerField()),
                ('WED', models.IntegerField()),
                ('THU', models.IntegerField()),
                ('FRI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M618Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('MON', models.IntegerField()),
                ('TUE', models.IntegerField()),
                ('WED', models.IntegerField()),
                ('THU', models.IntegerField()),
                ('FRI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M619Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('MON', models.IntegerField()),
                ('TUE', models.IntegerField()),
                ('WED', models.IntegerField()),
                ('THU', models.IntegerField()),
                ('FRI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M620Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('MON', models.IntegerField()),
                ('TUE', models.IntegerField()),
                ('WED', models.IntegerField()),
                ('THU', models.IntegerField()),
                ('FRI', models.IntegerField()),
            ],
        ),
    ]
